[project]
name = "aoc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "numpy>=2.1.3",
    "pysnooper>=1.2.1",
]
[tool.ruff]
line-length = 125
